(in-package :coleslaw)
(defun truex ()
  (let ((site-folder-local "~/truexeu/")
	(backup-folder "~/site-backups/"))
    (let ((site-folder-remote "/srv/http/"))
      (main site-folder-local)
      (asdf::run-program (format nil "rsync -r --rsh=\"/usr/bin/sshpass -f /home/jose/.backup-pass ssh -o StrictHostKeyChecking=no\" ~Astatic root@spensertruex.com:~Astatic" site-folder-local site-folder-remote))
      (asdf::run-program (format nil "tar -cjf ~Aarchive-~S.tar.bz2 ~A" backup-folder (get-universal-time) site-folder-local)))))
